version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: fatec
      MYSQL_DATABASE: siatt
      MYSQL_USER: myuser
      MYSQL_PASSWORD: fatec
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: